### ISSUE TITLE
Gzip Error when callig https://store.ui.com/...

### ISSUE THREAD

**Issue by timbarlotta** [JakeWharton/ui-spy#41]
Think I got this all setup but running via docker compose and I got a gzip error.

`Ubuntu 22.04`

```
Package: docker
Version: 1.5-2
```

```
Package: docker-compose-plugin
Version: 2.6.0~ubuntu-jammy
```

```text
docker images
REPOSITORY           TAG       IMAGE ID       CREATED        SIZE
jakewharton/ui-spy   latest    0169818947af   3 months ago   45MB
```

```toml
# The product handles (and their optional variant ID) to monitor for availability (required).
#  Value: Array of strings.
products = [
  "camera-g4-instant", "unifi-protect-g3-instant-camera",
]

# URL of IFTTT webhook to trigger for product availability changes (optional). If not specified, the
# tool will only log product availability changes to the console.
#  Value: Valid URL as string.
#  Default: none
ifttt = "https://maker.ifttt.com/trigger/ui-spy/with/key/<snip>"

# Duration between each check (optional).
#  Value: ISO 8601 duration string representing a positive value.
#    See https://en.wikipedia.org/wiki/ISO_8601#Durations.
#  Default: "PT1M" (1 minute)
#checkInterval = "PT5M"

# Base URL of the store (optional). Useful for targeting stores in other geographical markets.
#  Value: Valid URL as string.
#  Default: "https://store.ui.com"
#store = "https://ca.store.ui.com"

# Whether to also notify when a new product is added (optional).
#  Value: boolean
#  Default: false
productAddNotifications = true
```

```shell
docker compose up
[+] Running 1/0
 ⠿ Container ui-spy-ui-spy-1  Created                                                                              0.0s
Attaching to ui-spy-ui-spy-1
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:15 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0x14df6f8b != expected 0x2b650b4b
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:15 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0xb9738743 != expected 0xd4b9039a
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:15 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0xb434ddb9 != expected 0xac56394d
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:15 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0x9a1bf762 != expected 0x5a14547f
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:15 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0x0aaedd04 != expected 0xf9aef994
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:15 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0xd1fd8674 != expected 0xeafd0f47
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:16 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0xe38ec27a != expected 0x97115732
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:16 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0x037f5379 != expected 0x71dcec9a
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
ui-spy-ui-spy-1  | Aug 10, 2022 1:12:16 AM okhttp3.internal.platform.Platform log
ui-spy-ui-spy-1  | INFO: Callback failure for call to https://store.ui.com/...
ui-spy-ui-spy-1  | java.io.IOException: CRC: actual 0x74675810 != expected 0x50fed5f2
ui-spy-ui-spy-1  | 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
ui-spy-ui-spy-1  | 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
ui-spy-ui-spy-1  | 	at okio.GzipSource.read(GzipSource.kt:81)
ui-spy-ui-spy-1  | 	at okio.Buffer.writeAll(Buffer.kt:1642)
ui-spy-ui-spy-1  | 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:95)
ui-spy-ui-spy-1  | 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
ui-spy-ui-spy-1  | 	at com.jakewharton.uispy.UtilKt$await$2$1.onResponse(util.kt:21)
ui-spy-ui-spy-1  | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ui-spy-ui-spy-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
ui-spy-ui-spy-1  |
```

**Comment by JakeWharton** [comment]
Hello! Sorry you're having troubles.

On July 22nd the UI store seems to have switched from using Shopify to something else and they broke this tool. For now you can try one of the following alternative sources of getting notified of product availability:
- https://www.reddit.com/r/UbiquitiInStock/
- https://discord.gg/ubiquitiinstock
- https://uinotify.net/

I haven't decided what I'm going to do with this tool quite yet. I need to figure out the mechanism by which those three alternatives are getting their data and then I could conceivably switch to it. But I just haven't had the time to look.

I'll put a warning on the README for now.

**Comment by timbarlotta** [comment]
Appreciate the reply!  This all makes sense and if I find some time I'll poke around as well.

**Comment by stephenjamieson** [comment]
Wow that's most unfortunate.  Thank you for the tool though, I just snagged what I needed because of it a few days ago.
